/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author oscar
 */
public class PanelAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     * @param frame
     */
    public PanelAdministrador() {
        initComponents();       
        
        // Frame Padre
        //framePadre = frame;
        
        // Componentes
        panelEmpleado = new PanelEmpleado();
        panelCurso = new PanelCurso();
        panelReporte = new PanelReporte();
        // panelPrincipal = new PanelPrincipal();
        
        // Eventos
        EventosPanelPrincipal events = new EventosPanelPrincipal();
        asignarEventos(events);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIzq = new javax.swing.JPanel();
        botonEmpleado = new javax.swing.JButton();
        botonReportes = new javax.swing.JButton();
        botonCursos = new javax.swing.JButton();
        boton_2 = new javax.swing.JButton();
        boton_1 = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        panelDer = new javax.swing.JPanel();

        panelIzq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        botonEmpleado.setText("Empleado");

        botonReportes.setText("Generar Reportes");

        botonCursos.setText("Cursos");

        boton_2.setText("Opcion_2");

        boton_1.setText("Opcion_1");

        botonCerrar.setText("Cerrar Sesion");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelIzqLayout = new javax.swing.GroupLayout(panelIzq);
        panelIzq.setLayout(panelIzqLayout);
        panelIzqLayout.setHorizontalGroup(
            panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzqLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonReportes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonCursos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(boton_1, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelIzqLayout.setVerticalGroup(
            panelIzqLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelIzqLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(botonEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonReportes, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(boton_2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelDer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDer, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelDer, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonCursos;
    private javax.swing.JButton botonEmpleado;
    private javax.swing.JButton botonReportes;
    private javax.swing.JButton boton_1;
    private javax.swing.JButton boton_2;
    private javax.swing.JPanel panelDer;
    private javax.swing.JPanel panelIzq;
    // End of variables declaration//GEN-END:variables
    private PanelEmpleado panelEmpleado;
    private PanelCurso panelCurso;
    private PanelReporte panelReporte;

    /**
     * Nombre: actualizarPaneDer
     * Proposito: Metodo que actualiza el contenido del panelDer
     * @param panelNuevo 
     */    
    private void actualizarPaneDer(JPanel panelNuevo){
        panelDer.removeAll();
        panelDer.add(panelNuevo);
        panelDer.repaint();
        panelDer.updateUI();
    } // Fin del metodo actualizarPaneDer
    
    private void asignarEventos(EventosPanelPrincipal events) {      
        botonCursos.addActionListener(events);
        botonEmpleado.addActionListener(events);
        botonReportes.addActionListener(events);
        botonCerrar.addActionListener(events);
    } // Fin del metodo asignarEventos
    
    private class EventosPanelPrincipal implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == botonEmpleado) {
                actualizarPaneDer(panelEmpleado);
            }
            if (e.getSource() == botonCursos){  
                actualizarPaneDer(panelCurso);
            }
            if (e.getSource() == botonReportes) {
                actualizarPaneDer(panelReporte);
            }
            if (e.getSource() == botonCerrar) {
                // framePadre.actualizarPanelInferior(panelPrincipal);
            }
        }
    } // Fin de la clase EventosPanelPrincipal

} // Fin de la clase PanelPrincipal
