/** 
 * Nombre del Archivo: PanelCurso.java
 * Autores: JULIAN GARCIA RICO (1225435) 
 *          DIEGO FERNANDO BEDOYA (1327749) 
 *          CRISTIAN ALEXANDER VALENCIA TORRES (1329454) 
 *          OSCAR STEVEN ROMERO BERON (1326750) 
 */
package View;

import Logica.Curso;
import Logica.FaseCurso;
import Logica.FasePractica;
import Patrones.Item;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;

/**
 * Esta clase es cliente de Curso (Patron de diseño Composite) 
 */
public class PanelCurso extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelCurso() {
        initComponents();

        
        // Eventos 
        EventosPanelLogin events = new EventosPanelLogin();
        asignarEventos(events);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Practica = new javax.swing.JTabbedPane();
        panelCurso = new javax.swing.JPanel();
        panelSuperiorCurso = new javax.swing.JPanel();
        labelNombre = new javax.swing.JLabel();
        inputNombre = new javax.swing.JTextField();
        labelNombreCorto = new javax.swing.JLabel();
        inputNombreCorto = new javax.swing.JTextField();
        inputCodigo = new javax.swing.JTextField();
        inputDescripcion = new javax.swing.JTextField();
        labelDescripcion = new javax.swing.JLabel();
        labelCodigo = new javax.swing.JLabel();
        labelContenido = new javax.swing.JLabel();
        botonCurso = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputContenido = new javax.swing.JTextArea();
        panelInferiorCurso = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableFases = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        panelFase = new javax.swing.JPanel();
        panelSuperiorFase = new javax.swing.JPanel();
        labelCodCurso = new javax.swing.JLabel();
        labelCodFase = new javax.swing.JLabel();
        labelNumHoras = new javax.swing.JLabel();
        labelNumSemanas = new javax.swing.JLabel();
        labelTipo = new javax.swing.JLabel();
        inputCodigoCurso = new javax.swing.JTextField();
        inputNumSemanas = new javax.swing.JTextField();
        inputCodigoFase = new javax.swing.JTextField();
        inputNumHoras = new javax.swing.JTextField();
        labelContenidoFase = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inputContenidoFase = new javax.swing.JTextArea();
        botonFase = new javax.swing.JButton();
        inputTipo = new javax.swing.JComboBox();
        panelInferiorFase = new javax.swing.JPanel();
        panelPractica = new javax.swing.JPanel();
        panelSuperiorPractica = new javax.swing.JPanel();
        labelCodFasePrac = new javax.swing.JLabel();
        labelCodPrac = new javax.swing.JLabel();
        labelNomPrac = new javax.swing.JLabel();
        inputCodPractica = new javax.swing.JTextField();
        inputNombPrac = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        inputDescPrac = new javax.swing.JTextArea();
        labelDescPrac = new javax.swing.JLabel();
        botonPractica = new javax.swing.JButton();
        inputFasePrac = new javax.swing.JTextField();
        panelInferiorPractica = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(750, 505));

        panelCurso.setPreferredSize(new java.awt.Dimension(750, 505));

        panelSuperiorCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelNombre.setText("Nombre");

        labelNombreCorto.setText("Nombre corto");

        inputNombreCorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNombreCortoActionPerformed(evt);
            }
        });

        inputDescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputDescripcionActionPerformed(evt);
            }
        });

        labelDescripcion.setText("Descripción");

        labelCodigo.setText("Codigo");

        labelContenido.setText("Contenido");

        botonCurso.setText("Adicionar Curso");

        inputContenido.setColumns(20);
        inputContenido.setRows(5);
        jScrollPane2.setViewportView(inputContenido);

        javax.swing.GroupLayout panelSuperiorCursoLayout = new javax.swing.GroupLayout(panelSuperiorCurso);
        panelSuperiorCurso.setLayout(panelSuperiorCursoLayout);
        panelSuperiorCursoLayout.setHorizontalGroup(
            panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNombreCorto)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(inputCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                    .addComponent(inputNombreCorto, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNombre, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputDescripcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSuperiorCursoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonCurso)
                .addGap(299, 299, 299))
        );
        panelSuperiorCursoLayout.setVerticalGroup(
            panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelContenido))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorCursoLayout.createSequentialGroup()
                        .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNombreCorto)
                            .addComponent(inputNombreCorto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCodigo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDescripcion)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(botonCurso)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelInferiorCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tableFases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableFases);

        jLabel1.setText("Fases");

        javax.swing.GroupLayout panelInferiorCursoLayout = new javax.swing.GroupLayout(panelInferiorCurso);
        panelInferiorCurso.setLayout(panelInferiorCursoLayout);
        panelInferiorCursoLayout.setHorizontalGroup(
            panelInferiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorCursoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInferiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(110, 110, 110))
        );
        panelInferiorCursoLayout.setVerticalGroup(
            panelInferiorCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorCursoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panelCursoLayout = new javax.swing.GroupLayout(panelCurso);
        panelCurso.setLayout(panelCursoLayout);
        panelCursoLayout.setHorizontalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInferiorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelCursoLayout.setVerticalGroup(
            panelCursoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCursoLayout.createSequentialGroup()
                .addComponent(panelSuperiorCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferiorCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Practica.addTab("Curso", panelCurso);

        panelSuperiorFase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCodCurso.setText("Codigo Curso");

        labelCodFase.setText("Codigo Fase");

        labelNumHoras.setText("Numero Horas");

        labelNumSemanas.setText("Numero de Semanas");

        labelTipo.setText("Tipo");

        inputCodigoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCodigoCursoActionPerformed(evt);
            }
        });

        labelContenidoFase.setText("Contenido");

        inputContenidoFase.setColumns(20);
        inputContenidoFase.setRows(5);
        jScrollPane3.setViewportView(inputContenidoFase);

        botonFase.setText("Adicionar Fase");
        botonFase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFaseActionPerformed(evt);
            }
        });

        inputTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Presencial", "Virtual" }));

        javax.swing.GroupLayout panelSuperiorFaseLayout = new javax.swing.GroupLayout(panelSuperiorFase);
        panelSuperiorFase.setLayout(panelSuperiorFaseLayout);
        panelSuperiorFaseLayout.setHorizontalGroup(
            panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodFase, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCodCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumSemanas)
                            .addComponent(labelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputCodigoFase)
                            .addComponent(inputCodigoCurso)
                            .addComponent(inputNumSemanas)
                            .addComponent(inputNumHoras)
                            .addComponent(inputTipo, 0, 157, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelContenidoFase, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(botonFase)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        panelSuperiorFaseLayout.setVerticalGroup(
            panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(inputCodigoCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(labelContenidoFase))
                    .addComponent(labelCodCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputCodigoFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelCodFase))
                        .addGap(6, 6, 6)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNumHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumHoras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNumSemanas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumSemanas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTipo)
                            .addComponent(inputTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(panelSuperiorFaseLayout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addGap(18, 18, 18)))
                .addComponent(botonFase)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        panelInferiorFase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelInferiorFaseLayout = new javax.swing.GroupLayout(panelInferiorFase);
        panelInferiorFase.setLayout(panelInferiorFaseLayout);
        panelInferiorFaseLayout.setHorizontalGroup(
            panelInferiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInferiorFaseLayout.setVerticalGroup(
            panelInferiorFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelFaseLayout = new javax.swing.GroupLayout(panelFase);
        panelFase.setLayout(panelFaseLayout);
        panelFaseLayout.setHorizontalGroup(
            panelFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorFase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInferiorFase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelFaseLayout.setVerticalGroup(
            panelFaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFaseLayout.createSequentialGroup()
                .addComponent(panelSuperiorFase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferiorFase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Practica.addTab("Fase", panelFase);

        panelSuperiorPractica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        labelCodFasePrac.setText("Codigo Fase");

        labelCodPrac.setText("Codigo Practica");

        labelNomPrac.setText("Nombre");

        inputCodPractica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputCodPracticaActionPerformed(evt);
            }
        });

        inputDescPrac.setColumns(20);
        inputDescPrac.setRows(5);
        jScrollPane4.setViewportView(inputDescPrac);

        labelDescPrac.setText("Descripcion");

        botonPractica.setText("Adicionar Practica");

        javax.swing.GroupLayout panelSuperiorPracticaLayout = new javax.swing.GroupLayout(panelSuperiorPractica);
        panelSuperiorPractica.setLayout(panelSuperiorPracticaLayout);
        panelSuperiorPracticaLayout.setHorizontalGroup(
            panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                        .addComponent(labelCodPrac)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNomPrac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCodFasePrac, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addGap(34, 34, 34)
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputNombPrac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputCodPractica, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(inputFasePrac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelDescPrac))
                        .addGap(74, 74, 74))))
            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                .addGap(297, 297, 297)
                .addComponent(botonPractica)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelSuperiorPracticaLayout.setVerticalGroup(
            panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                .addGap(38, 53, Short.MAX_VALUE)
                .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCodFasePrac)
                            .addComponent(inputFasePrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCodPrac)
                            .addComponent(inputCodPractica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelSuperiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputNombPrac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNomPrac)))
                    .addGroup(panelSuperiorPracticaLayout.createSequentialGroup()
                        .addComponent(labelDescPrac)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addComponent(botonPractica)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        panelInferiorPractica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelInferiorPracticaLayout = new javax.swing.GroupLayout(panelInferiorPractica);
        panelInferiorPractica.setLayout(panelInferiorPracticaLayout);
        panelInferiorPracticaLayout.setHorizontalGroup(
            panelInferiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelInferiorPracticaLayout.setVerticalGroup(
            panelInferiorPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelPracticaLayout = new javax.swing.GroupLayout(panelPractica);
        panelPractica.setLayout(panelPracticaLayout);
        panelPracticaLayout.setHorizontalGroup(
            panelPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelSuperiorPractica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInferiorPractica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelPracticaLayout.setVerticalGroup(
            panelPracticaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPracticaLayout.createSequentialGroup()
                .addComponent(panelSuperiorPractica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInferiorPractica, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Practica.addTab("Practica", panelPractica);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Practica, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Practica)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputDescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputDescripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputDescripcionActionPerformed

    private void inputNombreCortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNombreCortoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNombreCortoActionPerformed

    private void inputCodigoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCodigoCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodigoCursoActionPerformed

    private void botonFaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFaseActionPerformed

    private void inputCodPracticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputCodPracticaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputCodPracticaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Practica;
    private javax.swing.JButton botonCurso;
    private javax.swing.JButton botonFase;
    private javax.swing.JButton botonPractica;
    private javax.swing.JTextField inputCodPractica;
    private javax.swing.JTextField inputCodigo;
    private javax.swing.JTextField inputCodigoCurso;
    private javax.swing.JTextField inputCodigoFase;
    private javax.swing.JTextArea inputContenido;
    private javax.swing.JTextArea inputContenidoFase;
    private javax.swing.JTextArea inputDescPrac;
    private javax.swing.JTextField inputDescripcion;
    private javax.swing.JTextField inputFasePrac;
    private javax.swing.JTextField inputNombPrac;
    private javax.swing.JTextField inputNombre;
    private javax.swing.JTextField inputNombreCorto;
    private javax.swing.JTextField inputNumHoras;
    private javax.swing.JTextField inputNumSemanas;
    private javax.swing.JComboBox inputTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel labelCodCurso;
    private javax.swing.JLabel labelCodFase;
    private javax.swing.JLabel labelCodFasePrac;
    private javax.swing.JLabel labelCodPrac;
    private javax.swing.JLabel labelCodigo;
    private javax.swing.JLabel labelContenido;
    private javax.swing.JLabel labelContenidoFase;
    private javax.swing.JLabel labelDescPrac;
    private javax.swing.JLabel labelDescripcion;
    private javax.swing.JLabel labelNomPrac;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNombreCorto;
    private javax.swing.JLabel labelNumHoras;
    private javax.swing.JLabel labelNumSemanas;
    private javax.swing.JLabel labelTipo;
    private javax.swing.JPanel panelCurso;
    private javax.swing.JPanel panelFase;
    private javax.swing.JPanel panelInferiorCurso;
    private javax.swing.JPanel panelInferiorFase;
    private javax.swing.JPanel panelInferiorPractica;
    private javax.swing.JPanel panelPractica;
    private javax.swing.JPanel panelSuperiorCurso;
    private javax.swing.JPanel panelSuperiorFase;
    private javax.swing.JPanel panelSuperiorPractica;
    private javax.swing.JTable tableFases;
    // End of variables declaration//GEN-END:variables

                
    private void asignarEventos(EventosPanelLogin events){
        botonCurso.addActionListener(events);
        botonFase.addActionListener(events);
        botonPractica.addActionListener(events);
    } // Fin del metodo asignarEventos
    
    private void ingresarCurso(){
        String nombreCompleto = inputNombre.getText();
        String nombreCorto = inputNombreCorto.getText();
        String Codigo = inputCodigo.getText();
        String Descripcion = inputDescripcion.getText();
        String Contenido = inputContenido.getText();
        
        //SOLO PARA TERCERA ENTRAGA DE PATRONES DE DISEÑO  
        boolean estado = true;
        Curso nuevoCurso = new Curso(nombreCompleto, nombreCorto, Codigo, 
                Descripcion, Contenido, estado);
        VentanaPrincipal.objCurso = nuevoCurso;
        
    } // Fin del metodo ingresarCurso           
    
    private void ingresarFase(){
        String codigoCurso = inputCodigoCurso.getText();
        String codigoFase = inputCodigoFase.getText();
        int numHoras = Integer.parseInt(inputNumHoras.getText());
        int numSemanas = Integer.parseInt(inputNumSemanas.getText());;
        String tipo = inputTipo.getSelectedItem().toString();
        String contenido = inputContenidoFase.getText();
        
        //SOLO PARA TERCERA ENTRAGA DE PATRONES DE DISEÑO        
        boolean estado = true;
        FaseCurso nuevaFase = new FaseCurso(codigoCurso, codigoFase, numHoras, 
                numSemanas, tipo, contenido, estado);
        VentanaPrincipal.objCurso.insertarItem(nuevaFase);        
    } // Fin del metodo ingresarFase
    
    private void ingresarPractica() {
        String codigoFase = inputFasePrac.getText();
        String codigoPractica = inputCodPractica.getText();
        String nombre = inputNombPrac.getText();
        String descripcion = inputDescPrac.getText();
        
        //SOLO PARA TERCERA ENTRAGA DE PATRONES DE DISEÑO
        boolean estado = true;
        FasePractica nuevaFasePractica = new FasePractica(codigoFase, codigoPractica, 
                nombre, descripcion, estado);
        
        int indiceObjFase = VentanaPrincipal.objCurso.obtenerItem(codigoFase);
        ArrayList <Item> listFases =  VentanaPrincipal.objCurso.getListFases();
        FaseCurso objFaseCurso = (FaseCurso)listFases.get(indiceObjFase);
        objFaseCurso.insertarItem(nuevaFasePractica);
        listFases.set(indiceObjFase, objFaseCurso);
        VentanaPrincipal.objCurso.setListFases(listFases);
    } // Fin del metodo ingresarPractica
    
    
    private void limpiarPanelFase(){
        
        //SOLO PARA TERCERA ENTRAGA DE PATRONES DE DISEÑO - MODIFICAR
        inputCodigoCurso.setText("");
        inputCodigoFase.setText("");
        inputNumHoras.setText("");
        inputNumSemanas.setText("");
        // inputTipo.getSelectedItem
        inputContenidoFase.setText("");                
    } // Fin del metodo limpiarPanelFase
    
    private void limpiarPanelPractica(){
        //SOLO PARA TERCERA ENTRAGA DE PATRONES DE DISEÑO - MODIFICAR
        inputFasePrac.setText("");
        inputCodPractica.setText("");
        inputNombPrac.setText("");
        inputDescPrac.setText("");        
    } // Fin del metodo limpiarPanelPractica
    
    private class EventosPanelLogin implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == botonCurso) {
                ingresarCurso();                
                //SOLO PARA TERCERA ENTRAGA DE PATRONES DE DISEÑO
                botonCurso.setEnabled(false);
                
            }
            if (e.getSource() == botonFase){
                ingresarFase();
                limpiarPanelFase();
            }
            if (e.getSource() == botonPractica){
                ingresarPractica();
                limpiarPanelPractica();
            }
        }   
    } // Fin de la clase EventosPanelLogin

} // Fin de la clase PanelLogin
