/** 
 * Nombre del Archivo: PanelLogin.java
 * Autores: JULIAN GARCIA RICO (1225435) 
 *          DIEGO FERNANDO BEDOYA (1327749) 
 *          CRISTIAN ALEXANDER VALENCIA TORRES (1329454) 
 *          OSCAR STEVEN ROMERO BERON (1326750) 
 */
package View;

import Controllers.ControladorSesion;
import Logica.Sesion;
import Patrones.FabricaPanelesUsuario;
import Patrones.FactoryIF;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 * Esta esta clase utiliza la clase GestorPanelesUsuarios (Fabrica)
 * para crear el panel correspondiente al tipo de usuario que inicie
 * sesion (Clase Cliente de de GestorPanelesUsuarios)
 */
public class PanelLogin extends javax.swing.JPanel {

    /**
     * Creates new form PanelLogin
     */
    public PanelLogin(VentanaPrincipal frame) {
        initComponents();
        // Frame Padre
        framePadre = frame;

        // Controlador
        contSesion = new ControladorSesion();
        fabricaPaneles = new FabricaPanelesUsuario();
        
        // Eventos 
        EventosPanelLogin events = new EventosPanelLogin();
        asignarEventos(events);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        inputUsuario = new javax.swing.JTextField();
        inputContrasena = new javax.swing.JPasswordField();
        botonIngresar = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setPreferredSize(new java.awt.Dimension(750, 505));

        labelUsuario.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelUsuario.setText("Usuario: ");

        labelContrasena.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        labelContrasena.setText("Contraseña: ");

        inputUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsuarioActionPerformed(evt);
            }
        });

        botonIngresar.setText("Ingresar");
        botonIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelUsuario)
                            .addComponent(labelContrasena))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(inputUsuario)
                            .addComponent(inputContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE))
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(317, 317, 317))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelUsuario)
                    .addComponent(inputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContrasena)
                    .addComponent(inputContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(botonIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsuarioActionPerformed

    private void botonIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonIngresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonIngresar;
    private javax.swing.JPasswordField inputContrasena;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
    private VentanaPrincipal framePadre;    
    private ControladorSesion contSesion;
    private FactoryIF fabricaPaneles;
            
    private void ingresar(){
        String usuario = inputUsuario.getText();
        String contrasena = new String(inputContrasena.getPassword());    
                
        // SE CREA LA SESION DE USUARIO
        Sesion objSesion = contSesion.ingresar(usuario, contrasena);    
        // SE UTILIZA LA FABRICA PARA TRAER EL PANEL SEUGUN EL TIPO DE USUARIO
        JPanel panelSesion = fabricaPaneles.createProduct(usuario);
        gestorVentana(panelSesion);
// TEMPORAL -> PARA INGREAR COMO UN TIPO DE USUARIO DEBEN colocar en "Usuario: "
//        "Administrador"  
//        "Master Teacher"  
//        "Leader Teacher"                   
//        "Coordinador"
    } // Fin del metodo ingresar
    
    
    private void limpiarCampos() {
        inputUsuario.setText("");
        inputContrasena.setText("");
    }
    
    private void gestorVentana (JPanel panelUsuario){
        if (panelUsuario != null){
            framePadre.actualizarPanelInferior(panelUsuario);
        } else {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado");
            limpiarCampos();        
        }        
    } // Fin del metodo gestorVentana 
    
    private void asignarEventos(EventosPanelLogin events){
        botonIngresar.addActionListener(events);
    } // Fin del metodo asignarEventos
    
    private class EventosPanelLogin implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {
            if (e.getSource() == botonIngresar) {
                ingresar();
            }
        }
    } // Fin de la clase EventosPanelLogin

} // Fin de la clase PanelLogin
