/** 
 * Nombre del Archivo: PanelCoordinador.java
 * Autores: JULIAN GARCIA RICO (1225435) 
 *          DIEGO FERNANDO BEDOYA (1327749) 
 *          CRISTIAN ALEXANDER VALENCIA TORRES (1329454) 
 *          OSCAR STEVEN ROMERO BERON (1326750) 
 */
package View;

import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;

/**
 * Esta se usa para el implementar el patron FABRICA
 * Representa un Producto Concreto
 */
public class PanelAdministrador extends javax.swing.JPanel {

    /**
     * Creates new form PanelPrincipal
     */
    public PanelAdministrador() {
        initComponents();       
        addMenu();
        // Componentes

        // Eventos
        EventosPanelAdministrador events = new EventosPanelAdministrador();
        asignarEventos(events);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelIzq = new javax.swing.JPanel();
        panelDer = new javax.swing.JPanel();

        panelIzq.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        panelDer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDer, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDer, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelDer;
    private javax.swing.JPanel panelIzq;
    // End of variables declaration//GEN-END:variables
    // PANELES 
    

    // MENU
    private JMenuBar barraLateral;  
    private JMenu menuCoordinador;// Coordinador
    private JMenuItem itemCrearCoor; // Coordinador
    private JMenuItem itemModificarCoor; // Coordinador
    private JMenuItem itemBuscarCoor; // Coordinador
    private JMenuItem itemEliminarCoor; // Coordinador    
    private JMenu menuMT; // MT   
    private JMenuItem itemCrearMT; // MT
    private JMenuItem itemModificarMT; // MT
    private JMenuItem itemBuscarMT; // MT
    private JMenuItem itemEliminarMT; // MT      
    private JMenu menuCurso; // Curso    
    private JMenuItem itemCrearCur; // Curso
    private JMenuItem itemModificarCur; // Curso
    private JMenuItem itemBuscarCur; // Curso
    private JMenuItem itemEliminarCur; // Curso  
    
     
    /**|
     * Nombre: actualizarPaneDer
     * Proposito: Metodo que actualiza el contenido del panelDer
     * @param panelNuevo 
     */    
    private void actualizarPaneDer(JPanel panelNuevo){
        panelDer.removeAll();
        panelDer.add(panelNuevo);
        panelDer.repaint();
        panelDer.updateUI();
    } // Fin del metodo actualizarPaneDer
    
    private void addImage(){
        JLabel labelImagne = new JLabel();
        ImageIcon img = new ImageIcon(getClass().getResource("/View/Image/Logounivalle.png"));
        labelImagne.setIcon(img);
        panelIzq.add(labelImagne);
    } // Fin del metodo addImage
    
    private void addMenu() {
        addImage();
        JPanel panelTemporal = new JPanel();
        panelTemporal.setBorder(BorderFactory.createEmptyBorder(20, 0, 50, 0));
        barraLateral = new JMenuBar();
        barraLateral.setLayout(new GridLayout(3, 1));

        // Menu Coordinador
        menuCoordinador = new JMenu("Coordinador"); 
        menuCoordinador.setPreferredSize(new Dimension(180, 50));
        menuCoordinador.setMenuLocation(180, 0);
        // Components
        itemCrearCoor = new JMenuItem("Crear"); // Coordinador
        itemModificarCoor = new JMenuItem("Modicar"); // Coordinador
        itemBuscarCoor = new JMenuItem("Buscar"); // Coordinador
        itemEliminarCoor = new JMenuItem("Eliminar"); // Coordinador    
        // Add Components
        menuCoordinador.add(itemCrearCoor);
        menuCoordinador.add(itemModificarCoor);
        menuCoordinador.add(itemBuscarCoor);
        menuCoordinador.add(itemEliminarCoor);
        
        // Menu MasterTeacher
        menuMT = new JMenu("Master Teacher");
        menuMT.setMenuLocation(180, 0);
        // Components 
        itemCrearMT = new JMenuItem("Crear"); // MT
        itemModificarMT = new JMenuItem("Modicar"); // MT
        itemBuscarMT = new JMenuItem("Buscar"); // MT
        itemEliminarMT = new JMenuItem("Eliminar"); // MT                     
        // Add Components
        menuMT.add(itemCrearMT);
        menuMT.add(itemModificarMT);
        menuMT.add(itemBuscarMT);
        menuMT.add(itemEliminarMT);
        
        // Menu Curso
        menuCurso = new JMenu("Curso"); // Curso    
        menuCurso.setMenuLocation(180, 0);
        // Components
        itemCrearCur = new JMenuItem("Crear"); // Curso
        itemModificarCur = new JMenuItem("Modificar"); // Curso
        itemBuscarCur = new JMenuItem("Buscar"); // Curso
        itemEliminarCur = new JMenuItem("Eliminar"); // Curso  
        // Add Components
        menuCurso.add(itemCrearCur);
        menuCurso.add(itemModificarCur);
        menuCurso.add(itemBuscarCur);
        menuCurso.add(itemEliminarCur);        
                
        // Add elements to JMenu
        barraLateral.add(menuCoordinador);
        barraLateral.add(menuMT);
        barraLateral.add(menuCurso);
        
        // Add to JPanel
        panelTemporal.add(barraLateral);
        panelIzq.add(panelTemporal);
        
    } // Fin del metodo addMenu
    
    private void asignarEventos(EventosPanelAdministrador events) {  
        // Menu Coordinador
        itemCrearCoor.addActionListener(events); 
        itemModificarCoor.addActionListener(events); 
        itemBuscarCoor.addActionListener(events); 
        itemEliminarCoor.addActionListener(events); 
        // Menu MT
        itemCrearMT.addActionListener(events); 
        itemModificarMT.addActionListener(events); 
        itemBuscarMT.addActionListener(events); 
        itemEliminarMT.addActionListener(events);    
        // Menu Curso
        itemCrearCur.addActionListener(events); 
        itemModificarCur.addActionListener(events); 
        itemBuscarCur.addActionListener(events); 
        itemEliminarCur.addActionListener(events);                   
    } // Fin del metodo asignarEventos
    
    private class EventosPanelAdministrador implements ActionListener{
        @Override
        public void actionPerformed(ActionEvent e) {
            // Menu Coordinador
            if (e.getSource() == itemCrearCoor) {
            }
            if (e.getSource() == itemModificarCoor) {            
            }
            if (e.getSource() == itemBuscarCoor) {            
            }
            if (e.getSource() == itemEliminarCoor) {            
            }
            // Menu de Master Teacher
            if (e.getSource() == itemCrearMT) {            
            }
            
            if (e.getSource() == itemModificarMT) {            
            }
            
            if (e.getSource() == itemBuscarMT) {            
            }
            if (e.getSource() == itemEliminarMT) {            
            }
            // Menu Cursos
            if (e.getSource() == itemCrearCur) {            
            }
            if (e.getSource() == itemModificarCur) {            
            }
            if (e.getSource() == itemBuscarCur) {            
            }
            if (e.getSource() == itemEliminarCur) {            
            }                  
        }
    } // Fin de la clase EventosPanelPrincipal

} // Fin de la clase PanelPrincipal
